windowrule {
    name = floating_tui
    match:class = ^(floating_tui)$
    float = on
    center = on
    size = 900 700
    stay_focused = on
}
windowrule {
  name = copyQ
  match:class = ^(com.github.hluk.copyq)$
  float = on
  center = on
  size = 800 500
  stay_focused = on
}
windowrule {
    name = ff_rule
    match:class = ^(firefox)$
    opacity = 1.0 override
}
decoration {
    rounding = 10 
    active_opacity = 0.9  # Slightly transparent when focused
    inactive_opacity = 0.9 # More transparent when not focused
    
    # Add blur to make it look like frosted glass
    blur {
        enabled = true
        size = 5 
        passes = 1 
    }
}
# 1. Removed the extra colon after 'class'
windowrule = suppress_event maximize, match:class .*

# 2. Changed 'nofocus' to 'no_focus' and removed extra colons in matches
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

